- next.config.ts
- package-lock.json
- package.json
- src/api/axiosInstance.ts
- src/api/category.ts
- src/api/products.ts
- src/api/user.ts
- src/components/home/Category.tsx
- src/components/home/Product.tsx
- src/components/home/ReviewerRanking.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/types/user.ts
"/" (홈 화면) 디자인 작업중
<br/>
<br/>
<br/>
아직 완성된 작업이 아닙니다. 정상적으로 개인 레포에 전달되는지 확인 차원에서 작업중인 부분을 PR한겁니다!
> feat/ category 컴포넌트, product 컴포넌트, reviewRanking 컴포넌트 작업중

- package-lock.json
- package.json
- src/pages/404.tsx
<br/>
- 이미지 직접 삽입 후 리팩토링 (예정)
- 모바일 퍼스트 확정 시 리팩토링 (예정)
- 404 페이지를 TypeScript 기반으로 작성했습니다.
- 반응형 기능을 추가하였습니다.
- 홈으로 가기 버튼을 누르면 메인 페이지로 이동합니다.
- 페이지 라우트 특성 상, 경로 설정이 없는 주소에 접속 시 404 페이지로 자동 연결됩니다.
- 추후 스타일 관련 변경이 있을 수 있습니다.
<br/>
<br/>
<br/>
- 모바일 퍼스트 확정 시 리팩토링 예정입니다. 
- 주석 처리로 부분 설명 하였습니다. 
- 경로 이탈 시 404 페이지가 자동 라우팅 됩니다.
- 모바일 기준 버튼 크기, 폰트 크기를 약 20% 축소하여 가독성을 개선했습니다.
<br/>
- [Next.js 공식 문서: Custom 404 Page](https://nextjs.org/docs/pages/building-your-application/routing/custom-error)
> feat: adjust mobile layout for 404 page

- src/api/category.ts
- src/api/products.ts
- src/api/user.ts
- src/components/home/Category.tsx
- src/components/home/Product.tsx
- src/components/home/ReviewerRanking.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/index.tsx
- 0428 멘토링 시간에 받았던 피드백 반영
- 홈 화면 반응형, 기초 디자인 영역 작업진행
- 카테고리 설정에 따른 productList 값 변경
- keyword, category, order, cursor 기본 api 파라미터 값 받을 수 있도록 설정
<br/>
<br/>
아직 세세한 디자인 및 요구사항 까지는 작업이 완료된 부분이 아닙니다!
api연동을 진행하면서 요구사항을 한꺼번에 진행할 예정입니다!
> feat: Home 화면 디자인 작업 및 api 연동 설정

- src/components/Modal.tsx
- src/components/home/Product.tsx
- src/pages/_document.tsx
- 공통 컴포넌트 모달 레이아웃 구현 완료했습니다.
- 현재 버튼 컴포넌트가 만들어지지 않은 상황이라 임의로 작성했습니다 버튼 컴포넌트 완료되는 대로 수정하겠습니다.
- 버튼 텍스트를  옵셔널 프로퍼티로 지정했습니다.
- 수정하면서 테스트하던 중에 홈 화면 Product 파일에서 이미지 경로에 오류가 나서 같이 수정해서 올렸습니다.
<br/>
<br/>
1. 모바일
2. 태블릿
3. pc
<br/>
필요한 모달 구현 시 공통 컴포넌트와 다른 내용이 있다면 style을 이용해 수정해서 사용해 주시면 됩니다.
(혹시 style이 적용되지 않은 부분 중에 수정이 필요하면 말씀해 주시면 바로 수정하겠습니다!)
혹시 궁금한 사항 있으시면 말씀해 주세요!!
<br/>
> feat: 공통 컴포넌트 모달 레이아웃 구현

- src/components/home/ReviewerRanking.tsx
- src/pages/index.tsx
- rounded-[99px] 대신 rounded-full로 수정
- products title에 p태그 대신 h4태그로 수정
<br/>
> fix: rounded-full로 수정, p 태그 대신 h4태그 사용

- next.config.ts
- src/api/products.ts
- src/components/home/Category.tsx
- src/components/home/InfiniteProductList.tsx
- src/components/home/Product.tsx
- src/components/home/ProductList.tsx
- src/hooks/useInfiniteList.ts
- src/pages/index.tsx
- 쿼리 파라미터 ex)keyword, category 에 따른 동적인 데이터 바인딩
- 카테고리 선택후 모바일 화면에서 카테고리 항목이 보이도록 추가 작업
- 카테고리 및 키워드가 적용된 productList에 무한 스크롤 적용
cursor를 활용한 무한 스크롤 기능 구현
order 로 별점순을 선택했을 경우
> feat: 쿼리 파라미터에 따른 동적 데이터 렌더링

- src/components/input/loginInput.tsx
- src/pages/signup.tsx
- src/types/auth.ts
<br/>
회원가입 기능 구현
<br/>
<br/>
<br/>
타입 파일에서 회원가입 관련한 api type 변경했습니다
<br/>
> feat:회원가입 기능 추가

- src/api/auth.ts
- src/api/axiosInstance.ts
- src/components/home/Product.tsx
- src/pages/signup.tsx
<br/>
axiosInstance baseURL주소 팀ID 하드코딩으로 변경했습니다
<br/>
<br/>
<br/>
baseURL변경으로 인해 API작업하실때 팀id부분은 제거하고 사용하시면될꺼같습니다 추후에 문제가 생긴다면 수정하겠습니다
<br/>
> Style: baseURL팀 id 하드코딩으로 변경

- src/components/home/Product.tsx
- components/home/Product.tsx 에서 잘못 import된 이미지를 삭제했습니다.
> fix: import delete

- src/pages/login.tsx
login 페이지 스타일 변경
<br/>
<br/>
<br/>
네비바랑 버튼은 작업해주시는데로 넣어서 수정하겠습니다
구글이라 카카오 외각선도 그때 추가하겠습니다
> Design: 로그인 페이지 스타일 설정

- src/api/axiosInstance.ts
- src/components/home/Category.tsx
- src/components/home/Product.tsx
- src/pages/index.tsx
- mobile 사이즈에서 category 애니메이션 구현
https://github.com/user-attachments/assets/81028141-022c-4273-a1e4-875aa3f10720
- 해당 작업은 HeaderNav 작업이 완료되면 "테스트"button이 삭제될 예정입니다 현재는 임시로 사용중입니다!
> feat: category animation 구현

- src/components/Modal.tsx
- 필요한 스타일을 적용할 수 있도록 style에서 containerStyle, buttonStyle로 분리했습니다.
- 모달 컴포넌트 사용 시 document is not defined 오류가 발생해 코드를 수정했습니다.
<br/>
<br/>
> fix: 모달 공통 컴포넌트 수정

- next.config.ts
- src/api/user.ts
- src/components/FollowUserListModal.tsx
- src/pages/index.tsx
- src/types/user.ts
- user.ts Type중 FollowUserItem 속성중에 followee 부분을 follower로 수정하였습니다. (swagger에서는 followee였는데 막상 받아서 확인해 보니 follower로 되어 있었습니다. )
- next.config 파일에서 image 도메인을 추가하였습니다. (next Image 컴포넌트에서 외부 사이트에서 가져오는 걸 막아서 추가하였습니다.)
- 유저 팔로우 목록 모달을 작성하였습니다.
<br/>
<br/>
<br/>
> Feature/followUserListModal 

- src/components/button/button.tsx
<br/>
이런 식으로 사용하시면 됩니다 !
import Button from "@/components/button/Button";
Primary Large
<Button variant="primary" size="l">가입하기</Button>
Secondary Medium
<Button variant="secondary" size="m">가입하기</Button>
Tertiary Small
<Button variant="tertiary" size="s">가입하기</Button>
<br/>
<br/>
<br/>
pull 받고 npm i 한 뒤에 사용해주세요
<br/>
> feat: button 구현

- src/api/image.ts
- src/components/ImageUploader.tsx
- 기본 레이아웃 구현 완료했습니다.
- 에러 메시지는 임시로 구현한 것이고 수정 예정입니다.
- 이미지 선택 후 x 버튼에 피그마와 다른 부분이 있어 이것도 추가로 수정 예정입니다.
<br/>
<br/>
1. 이미지 등록 시
2. 이미지 크기가 5MB를 넘는 경우
<br/>
<br/>
> feat: 공통 컴포넌트 imageUploader 레이아웃 구현

- src/components/Textarea.tsx
- onChange를 prop으로 받을 수 있도록 코드를 수정했습니다.
- prop으로 받던 height를 삭제했습니다.(추후 필요한 경우 협의 후 수정하겠습니다.)
- 글자 수가 많아지면 숫자 카운팅 되는 부분과 텍스트가 겹치는 문제가 있어 추후 수정 예정입니다.
- 아직 focus 시 보더에 그라디언트 효과 구현을 완성하지 못했습니다. 이것도 추후 수정 예정입니다.
<br/>
<br/>
> refactor: Textarea 수정

- src/components/ProductForm.tsx
#72
- button 컴포넌트 -> Button 컴포넌트로 수정
> fix: button 컴포넌트 대문자 수정

- src/components/home/Product.tsx
#74 
- infiniteProductList -> Product 컴포넌트의 onClick props를 optional로 수정했습니다.
> fix: Product 컴포넌트 onClick props optional로 수정

- package-lock.json
- package.json
- src/components/Modal.tsx
- src/components/ProductReviewModal.tsx
- src/components/StarRating.tsx
- 아직 상품 상세 화면 구현이 완료되지 않아 데이터가 불러와지지 않아 에러가 발생합니다.
- 상품 상세 화면이 구현 완료되면 모달 구조는 변경 예정입니다.
- 이미지를 여러 개 추가하는 것은 이미지 업로더 수정하면서 같이 수정 예정입니다.
- 반응형 구현을 위해 모달 공통 컴포넌트의 height 값을 auto로 수정하면서 containerStyle prop을 삭제했습니다.
<br/>
<br/>
아래의 사진은 직접 productId 값을 설정해 테스트한 결과물입니다.
1. PC 버전
2. 태블릿 버전
3. 모바일 버전
<br/>
pull 받으신 후에 npm install 해주셔야 합니다!
<br/>
> feat: 상품 리뷰 모달 구현

- src/components/Textarea.tsx
- textarea 포커스 시 보더에 그라디언트 적용하도록 수정했습니다.
<br/>
<br/>
1. PC 버전
2. 태블릿 버전
3. 모바일 버전
<br/>
> refactor: Textarea 포커스 시 보더 그라디언트 적용

- src/components/ProductReviewModal.tsx
- src/components/StarRating.tsx
- 피드백 주신 부분 반영해서 적용했습니다.
- 필요 없는 코드 삭제했습니다.
<br/>
> refactor: 상품 리뷰 모달 피드백 반영

- src/lib/kakaoSignupAuth.ts
- src/pages/kakaologin.tsx
- src/pages/oauth/signup/kakao.tsx
카카오 로그인 회원가입 배포 사이트 주소에 맞게 redirectUrl 변경 및 카카오 로그인 상태관리 코드 추가
<br/>
> Refactor:배포 환경에 맞게 redirectUrl 변경

- src/components/DropDown.tsx
- src/components/ProductForm.tsx
- src/components/home/Category.tsx
- src/components/home/InfiniteProductList.tsx
- src/components/home/ReviewerRanking.tsx
- src/pages/index.tsx
- 리뷰어 랭킹에서 사용자 이미지가 있으면 표시되도록 수정
- 모바일 카테고리 핸들러 추가
- 카테고리 z-index를 수정해서 Modal과 겹치지 않도록 수정
- 상품 추가 & 상품 편집 상품명 Input 에 label 제거
- 모바일 Sort 적용
- home 컴포넌트 layout 수정
<br/>
<br/>
- 전
- 후
---
- 전
- 후
---
- 전
-후
---
- 전
- 후
---
- 전
- 후
---
- 전
- 후
> fix: home 전반적으로 수정

- src/components/EditProfileModal.tsx
- src/components/ProductForm.tsx
- src/components/ProductReviewModal.tsx
- src/components/Textarea.tsx
- 최대 작성 가능한 숫자가 달라 maxLength를 prop으로 설정해 300자, 500자까지 작성 가능하도록 수정했습니다.
<br/>
<br/>
- 프로필 편집 모달, 상품 추가/편집 모달에 maxLength 다 적용했습니다.
<br/>
> refactor: maxLength prop 추가

- src/pages/mypage.tsx
#113
<br/>
- onChange의 타입 수정
<br/>
> fix: onChange 타입 수정

- src/pages/mypage.tsx
#122
<br/>
- myPage Api import
<br/>
> fix: mypage api import 및 타입 수정

- src/pages/compare.tsx
- 비교하기 상품 localStorage에 저장
<br/>
<br/>
> feat: 비교하기 상품 localStorage에 저장

- next.config.js
- src/components/products/ProductDetail.tsx
- src/components/products/ProductDetailButtonGroup.tsx
- src/components/products/ProductDetailLayout.tsx
- src/components/products/ProductReviews.tsx
- src/components/products/ProductStatistics.tsx
- src/components/products/ReviewSortDropdown.tsx
- src/components/products/StatisticCard.tsx
- src/pages/products/[id].tsx
#131
<br/>
상품 상세 페이지 ui 및 api 구현 100% 완성된 상태는 아님 반응형 작업까지 완료
<br/>
<br/>
> feat: 상품 상세 페이지 구현

- src/components/input/loginInput.tsx
<br/>
비밀번호 input 눈 아이콘 올라가는 현상을 수정했습니다
<br/>
<br/>
<br/>
<br/>
> Design:비밀번호 input UI 수정

- src/components/CheckReplacementModal.tsx
- compare 페이지로 이동과 기본 UI 구현 완료했습니다.
- 비교 상품 교체 모달 완료 후 연동 예정입니다.
<br/>
<br/>
> feat: 비교 상품 교체 모달 바로가기 UI 구현

- src/pages/products/[id].tsx
- 'use client' 문구를 제거합니다. (저희 프로젝트는 page Router라 use client 사용못합니다.)
<br/>
> use client 삭제

- src/api/review.ts
- src/components/EditProductReviewModal.tsx
- src/components/products/ProductDetailButtonGroup.tsx
- src/components/products/ProductReview.tsx
<br/>
- 상품 리뷰 모달과 수정 모달 구현 및 연결 완료 했습니다.
<br/>
<br/>
> Feat: 상품 리뷰 및 수정 모달 구현 완료

- src/api/review.ts
- src/components/EditProductReviewModal.tsx
- src/components/ImageUploader.tsx
- src/components/Modal.tsx
- src/components/ProductForm.tsx
- src/components/ProductReplacementAlertModal.tsx
- src/components/ProductReviewModal.tsx
- src/components/home/Category.tsx
- src/components/home/Product.tsx
- src/components/products/ProductDetailButtonGroup.tsx
- src/components/products/ProductReview.tsx
- src/components/products/ProductReviews.tsx
- src/components/products/ReviewDeleteConfirm.tsx
- 태블릿 반응형 사이즈에서 홈화면 카테고리 텍스트가 깨지는 부분 수정
- 상품 별점을 소수점 한 자릿수 까지만 표현하도록 수정
- 상품 상세 페이지 리뷰 없을 경우 나오는 영역 사이즈 조절
- 상품 상세 페이지에서 리뷰 작성시 데이터 즉시 반영되도록 수정
- 상품 상세 페이지에서 리뷰 수정시 데이터 즉시 반영되도록 수정
- 상품 상세 페이지에서 리뷰 삭제 기능 구현 및 즉시 반영되도록 구현
- 상품 추가 및 편집시 이미지 없을 경우 나타나는 alert 수정
- 상품 상세 페이지 상품 수정 Modal 연결및 데이터 즉시 반영되도록 수정
- 비교하기 기능 연결
<br/>
<br/>
<br/>
제가 발견한 오류 사항과 수정 사항들은 모두 작업해서 올려두었습니다!
남은 에러가 있을 수 있습니다! 테스팅 부탁드립니다!
@juha399 시연영상 제작에 앞서 위의 부분의 모든 값들을 제거하고 처음부터 테스트 및 영상 촬영 부탁드립니다!
> fix: 최종 전체적으로 수정
